# Pull the base image from Ubuntu
FROM ubuntu:latest AS base

RUN echo "Loading ES dataloader code and dependencies"

RUN apt-get update \
 && apt-get install -y python3 python3-pip git

RUN echo "cloning dataloader code" \
 && git clone --single-branch --branch master --recurse-submodules -j8 https://github.com/CBIIT/icdc-dataloader.git /usr/local/icdc_dataloader \
 && cd /usr/local/icdc_dataloader \
 && pip3 install -r requirements.txt

# Data loading phase
FROM base AS load_data

# break caching for lines below this. This allows reloading data on every build without re-running setup tasks
ADD https://www.timeanddate.com/worldclock/usa/baltimore /tmp/bustcache

ARG BACKEND_SOURCE_FOLDER
ARG NEO4J_PASS
ENV Neo4jPass=${NEO4J_PASS}
ARG NEO4J_USER
ENV Neo4jUser=${NEO4J_USER}
ARG NEO4J_HOST
ENV Neo4jHost=${NEO4J_HOST}

# Copy data and config files to the container
ADD ${BACKEND_SOURCE_FOLDER} /usr/local/bento-backend

# copy indices file from backend
RUN cp /usr/local/bento-backend/src/main/resources/yaml/es_indices_bento.yml /usr/local/icdc_dataloader/config/es_indices_bento.yml

# update the neo4j credentials in the dataloader config file
RUN cp /usr/local/icdc_dataloader/config/es_loader.yml.j2 /usr/local/icdc_dataloader/config/es_loader_local.yml \
 && sed -i "s/{{ neo4j_password }}/${NEO4J_PASS}/g" /usr/local/icdc_dataloader/config/es_loader_local.yml \
 && sed -i "s/{{neo4j_ip}}/${NEO4J_HOST}/g" /usr/local/icdc_dataloader/config/es_loader_local.yml \
 && sed -i "s/{{ es_host }}/bento-es/g" /usr/local/icdc_dataloader/config/es_loader_local.yml

ENTRYPOINT echo "loading data from neo4j" \
 && cd /usr/local/icdc_dataloader \
 && python3 es_loader.py config/es_indices_bento.yml config/es_loader_local.yml \
 && /bin/bash